.TH opt2lfp 1 opt2lfp\-0.0.1
.SH NAME
opt2lfp \- convert opticon opt to relativity lfp
.SH SYNOPSIS
.B opt2lfp [OPTFILE]
.SH DESCRIPTION
opt2lfp converts an opt file specified on the command line
or from standard in 
to an lfp on standard out.
.SH OPTIONS
none
.SH EXAMPLES
opt2lfp sample.opt >sample.lfp
.SH SEE ALSO
.SH BUGS
Does not handle multi-image files correctly.
Probably others.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
