.TH count-iocr 1 count-iocr\-0.0.1
.SH NAME
count-iocr \- provide ocr stats from IPRO ecap ocr summaries
.SH SYNOPSIS
.B count-iocr 
.SH DESCRIPTION
count-iocr sums up GRAND TOTAL lines from all files 
named on the command line
.SH OPTIONS
none
.SH EXAMPLES
count-iocr *ocr.csv
.SH FILES
.SH SEE ALSO
.SH BUGS
Doesn't check that we are really looking at ecap ocr summaries.
Probably others.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
