.TH b2gb 1 b2gb\-0.0.1
.SH NAME
b2gb \- convert bytes to gigabytes
.SH SYNOPSIS
.B b2gb NUMBER_OF_BYTES
.SH DESCRIPTION
b2gb puts gigabytes on standard out
from bytes supplied on the commmand line.
These are binary gigabytes
(sometimes known as gibibytes).
Commas and quotes are removed.
.SH OPTIONS
none
.SH EXAMPLES
b2gb 1,234,567
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
