.TH lfp2meta 1 lfp2meta\-0.0.1
.SH NAME
lfp2meta \- generate a metadata csv from an lfp file
.SH SYNOPSIS
.B lfp2meta LFPFILE
.SH DESCRIPTION
lfp2meta accepts an lfp file and prints a csv with
BEGDOC, ENDDOC, BEGATTACH, ENDATTACH, ID, PGCOUNT, TYPE, and ATTACHCOUNT
fields on standard output.
.SH OPTIONS
none
.SH EXAMPLES
lfp2meta foo.lfp >'foo MetaData.csv'
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
