.TH prt-split 1 prt-split\-0.0.1
.SH NAME
prt-split \- Break a prt file on specified lines.
.SH SYNOPSIS
.B prt-split PRTFILE BREAKLISTFILE [OUTPUTDIR]
.SH DESCRIPTION
prt-split generates multiple prt files from a single one,
using a list of image keys to break on. The new prts are 
placed in a folder (by default called 'out').
.SH OPTIONS
none
.SH EXAMPLES
prt-split PRTFILE BREAKLISTFILE
.SH BUGS
Probably.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
