#!/bin/sh

while :; do
    cat [0-9][0-9][0-9][0-9].LOG 2>/dev/null && break
    echo "waiting for ocr to be done..."
    echo "$(find [0-9][0-9][0-9][0-9] -type f | wc -l) text made"
    sleep 5
done

sleep 10
