.TH watch-iocr 1 watch-iocr\-0.0.1
.SH NAME
watch-iocr \- wait for Ipro ocr to complete.
.SH SYNOPSIS
.B watch-iocr 
.SH DESCRIPTION
watch-iocr waits for Ipro ocr to be completed.
It is mainly intended for use in shell scripts and makefiles.
It should be run from the root of the Ipro ocr project directory.
.SH OPTIONS
none
.SH SEE ALSO
robo-iocr(1).
.SH BUGS
Probably.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
