.TH clean-ibuild 1 clean-ibuild\-0.0.1
.SH NAME
clean-ibuild \- clean up an IPRO build directory 
.SH SYNOPSIS
.B clean-ibuild [-p]
.SH DESCRIPTION
clean-ibuild removes various detritus left by IPRO build,
and optionally moves IMAGES/00/00 to PDF
.SH OPTIONS
-p treat build as a pdf build
.SH EXAMPLES
clean-ibuild 
.SH FILES
.SH SEE ALSO
.SH BUGS
-p fails if more than one image directory.
Probably others.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
