.TH fieldedcount 1 fieldedcount\-0.0.1
.SH NAME
fieldedcount \- count billable scan time coding in IPRO's FIELDED.txt
.SH SYNOPSIS
.B fieldedcount FIELDED.txt
.SH DESCRIPTION
fieldedcount outputs the number of unique code changes recorded
in in fields 6 to end of a csv.
.SH OPTIONS
none
.SH EXAMPLES
fieldedcount FIELDED.txt
.SH FILES
.SH SEE ALSO
.SH BUGS
Should be variable to other fields.
Probably others.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
