.TH statdat 1 statdat\-0.0.1
.SH NAME
statdat \- extract useful summary from a concordance dat file
.SH SYNOPSIS
.B statdat DATFILE
.SH DESCRIPTION
.B statdat
accepts a single dat file as an argument and prints
line count and some other stuff to standard out.
.SH OPTIONS
none
.SH EXAMPLES
statdat example.dat
.SH FILES
.SH SEE ALSO
.SH BUGS
Essentially vaporware.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
