.TH lfp2opt 1 lfp2opt\-0.0.1
.SH NAME
lfp2opt \- generate a Concordance style opt file from an lfp
.SH SYNOPSIS
.B lfp2opt LFPFILE
.SH DESCRIPTION
lfp2opt generates an opt file on standard out from an lfp
supplied on the command line or on standard input.
.SH OPTIONS
none
.SH EXAMPLES
lfp2opt sample.lfp >sample.opt
.SH BUGS
Probably.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
