#!/usr/bin/awk -f

BEGIN {
    FS = ","
}

/^IM,/ {

    if ($3 ~ /[A-Z]/) {
        if (NR > 1)
            printdoc()
        imgc = 0
    }

    imgc++
    split($5, a, /;/)
    vol = a[1]
    sub(/^@/, "", vol)
    path = a[2]
    img = a[3]
    key = $2
    line[imgc] = sprintf("%s,%s,X:\\%s\\%s", key, vol, path, img)
}

END {
    printdoc()
}

function printdoc() {
    printf("%s,Y,,,%d\r\n", line[1], imgc)
    for (i = 2; i <= imgc; i++) {
        printf("%s,,,,\r\n", line[i])
    }
}
