.TH lfpdebreak 1 lfpdebreak\-0.0.1
.SH NAME
lfpdebreak \- generate an lfp to remove all breaks from existing lfps
.SH SYNOPSIS
.B lfpdebreak LFPFILE1 [LFPFILES...]
.SH DESCRIPTION
lfpdebreak prints BF lfp lines to standard out for all doc breaks
in the lfps supplied on the command line.
.SH OPTIONS
none
.SH EXAMPLES
lfpdebreak LFPFILE1 >debreak.lfp
.SH BUGS
Probably.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
