.TH lfp2subdirsbat 1 lfp2subdirsbat\-0.0.1
.SH NAME
lfp2subdirsbat \- create a batch file for subdirectories from an lfp
.SH SYNOPSIS
.B lfp2subdirsbat LFPFILE
.SH DESCRIPTION
.B lfp2subdirsbat
creates two bat files which can be run from the text directories of
a build to reorganize text files as per image files.
.SH OPTIONS
none
.SH EXAMPLES
lfp2subdirsbat LFPFILE
.SH FILES
.B single.bat, multi.bat
.br
The output files
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
