.TH lfpfolderbreak 1 lfpfolderbreak\-0.0.1
.SH NAME
lfpfolderbreak \- generate parent break lfp for each folder change
.SH SYNOPSIS
.B lfpfolderbreak LFPFILE [LFPFILES...]
.SH DESCRIPTION
lfpfolderbreak generates a BM lfp on standard out, one line for
every change in folder structure of the lfps provided on the
command line.
.SH OPTIONS
none
.SH EXAMPLES
lfpfolderbreak LFPFILE [LFPFILES...] >rebreak.lfp
.SH FILES
.SH SEE ALSO
lfpdebreak(1)
.SH BUGS
Probably.
This version has not been tested at all.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
