.TH lfp2folderbat 1 lfp2folderbat\-0.0.1
.SH NAME
lfp2folderbat \- generate a batch file to make folders from an lfp
.SH SYNOPSIS
.B lfp2folderbat LFPILE
.SH DESCRIPTION
lfp2folderbat accepts an lfp file and generates mover.bat, which
creates folders per FD flag and moves pdfs to the folders.
.SH OPTIONS
none
.SH EXAMPLES
lfp2folderbat LFPILE
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
