.TH catalog 1 catalog\-0.0.1
.SH NAME
catalog \- print file extensions of all files in current directory
.SH SYNOPSIS
.B catalog [PATHS]
.SH DESCRIPTION
catalog prints a list, with counts, 
of all file extensions in the specified directories
(defaulting to .)
.SH OPTIONS
none
.SH EXAMPLES
catalog 
.SH FILES
/tmp/list
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2012, 2013 Noah Birnel
.sp
You may use this software however you like.
