#!/bin/sh

if [ $#  -gt 0 ]; then
    find "$@" -type f | sort -u >/tmp/list
else
    find . -type f | sort -u >/tmp/list
fi

awk -F'/' '{ printf("%s\n", tolower($NF)) }' /tmp/list |\
awk -F.   '{ print $NF }' |\
sort | uniq -c |\
awk '
    { 
        total += $1
        printf("%7d %s\n", $1, $2)
    }
    END { printf("%7d total\n", total) }'


