.TH statbegend 1 statbegend\-0.0.1
.SH NAME
statbegend \- get doc count and range from a beg end file
.SH SYNOPSIS
.B statbegend BEGENDFILE
.SH DESCRIPTION
.B statbegend 
accepts a single file as an argument and prints line count
and beginning and ending range to standard out.
.SH OPTIONS
none
.SH EXAMPLES
statbegend example_beg_end.txt
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
