#!/usr/bin/awk -f

BEGIN {
    FS = OFS = "," 
    ORS = "\r\n"
    pad = 6
    begnum = 1
    padfmt = sprintf("%%0%dd", pad)
}

$1 == "IM" {
    $2 = sprintf(padfmt, begnum)
    begnum++
}

{ print }
