#!/usr/bin/awk -f

BEGIN {
    FS = OFS = "," 
    ORS = "\r\n"
    prefix = "CTRL"
    pad = 6
    begnum = 1
    # our default format will be CTRL%06d
    fmt = sprintf("%s%%0%dd", prefix, pad)
}

$1 == "IM" {
    $2 = sprintf(fmt, begnum)
    begnum++
}

{ print }
