.TH lfp2dii 1 lfp2dii\-0.0.1
.SH NAME
lfp2dii \- generate a dii from an lfp file
.SH SYNOPSIS
.B lfp2dii LFPFILE
.SH DESCRIPTION
lfp2dii accepts an lfp file and prints a dii on standard output.
.SH OPTIONS
none
.SH EXAMPLES
lfp2dii foo.lfp >'foo @I.DII'
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
