.TH rotate 1 rotate\-0.0.1
.SH NAME
rotate \- rotate landscaped images
.SH SYNOPSIS
.B rotate FILES
.SH DESCRIPTION
rotate creates new image files from files specified on the command line.
If the original image is wider than it is tall,
the new image will be rotated 90\(de counterclockwise.
The new image file will be named _rot_FILE,
where 
.B FILE
is the original filename.
.SH OPTIONS
none
.SH EXAMPLES
rotate INPUTFILE.jpg
.SH FILES
.SH SEE ALSO
.SH BUGS
No option to rotate clockwise.
Probably others.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
