.TH statopt 1 statopt\-0.0.1
.SH NAME
statopt \- extract useful summary from a concordance opt file
.SH SYNOPSIS
.B statopt OPTFILE
.SH DESCRIPTION
.B statopt
accepts a single opt file as an argument and prints
image count, tiff count, jpg count, range etc to 
standard out.
.SH OPTIONS
none
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
