.TH prt-uncollate 1 prt-uncollate\-0.0.1
.SH NAME
prt-uncollate \- uncollate the documents in a prt
.SH SYNOPSIS
.B prt-uncollate PRT NUMSETS
.SH DESCRIPTION
prt-uncollate writes an uncollated prt to standard out
from a prt supplied on the command line.
.SH OPTIONS
none
.SH EXAMPLES
prt-uncollate sample.prt 3 >x3sample.prt
.SH SEE ALSO
prt-split(1)
.SH BUGS
Probably.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
