.TH dii2begend 1 dii2begend\-0.0.1
.SH NAME
dii2begend \- Create a beg-end from a summation dii
.SH SYNOPSIS
.B dii2begend SUMM.dii
.SH DESCRIPTION
dii2begend prints beginning and end ranges to standard
out from @T and @C ENDDOC lines in a dii
.SH OPTIONS
none
.SH EXAMPLES
dii2begend SUMM.dii >'Beg End.txt'
.SH FILES
.SH SEE ALSO
.SH BUGS
only works for @T and @C ENDDOC formats.
.sp
Probably others.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
