.TH html2pdf 1 html2pdf\-0.0.1
.SH NAME
html2pdf \- Create pdfs from html documents
.SH SYNOPSIS
.B html2pdf FILE1 [FILE2...]
.SH DESCRIPTION
html2pdf creates a pdf document from each html document 
supplied. 
.SH OPTIONS
none
.SH EXAMPLES
html2pdf FILE1 [FILE2...]
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
