.TH prt-rename 1 prt-rename\-0.0.1
.SH NAME
prt-rename \- rename prts after their first document
.SH SYNOPSIS
.B prt-rename PRTFILE [PRTFILE...]
.SH DESCRIPTION
prt-rename renames one or more prt files after their first
documents. 
.SH OPTIONS
none
.SH SEE ALSO
prt-split(1), prt-uncollate(1)
.SH BUGS
Probably.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
