#!/bin/sh

#FIXME just the BEGEND lines are good, print to stdout
#FIXME allow integrating a begend, or lfp to get begend
ls "$@" | sort -u | awk '
{ 
    sub(/\.[^.]*$/, "")
    num = file = $0
    sub(/^.*[^0-9]+0*/, "", num)
}

NR == 1 {
    begn = lastn = num
    begf = lastf = file
    ranges = 1
}

NR != 1 {
    if (num + 0  != lastn + 1) {
        if (begn == lastn) { printf("%s\n", begf) }
        else               { printf("%s,%s\n", begf, lastf) }
        ranges++
        begn = num
        begf = file
    }
    lastn = num
    lastf = file
}

END {
    if (begn == lastn) { printf("%s\n", begf) }
    else               { printf("%s,%s\n", begf, lastf) }
    printf("%d in %d ranges\n", NR, ranges)
}
'
