.TH debom 1 debom\-0.0.1
.SH NAME
debom \- remove byte order mark
.SH SYNOPSIS
.B debom [FILE]
.SH DESCRIPTION
debom removes the byte order mark from a file provided on the command line,
or from standard in,
and prints to standard out.
.SH OPTIONS
none
.SH EXAMPLES
debom UTF-8_FILE >NICE-UTF-8_FILE
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
Watch for line endings.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
