.TH watch-ibuild 1 watch-ibuild\-0.0.1
.SH NAME
watch-ibuild \- wait for an Ipro build to complete
.SH SYNOPSIS
.B watch-ibuild LFPFILE NIMAGES
.SH DESCRIPTION
watch-ibuild waits for an lfp file to have a given number of image
lines in it.
It is mainly intended for use in shell scripts and makefiles.
.SH OPTIONS
none
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
