.TH dii-renum 1 dii-renum\-0.0.1
.SH NAME
dii-renum \- renumber the records in a dii file
.SH SYNOPSIS
.B dii-renum DIIFILE
.SH DESCRIPTION
dii-renum renumbers all records in a dii file supplied
on the command line, 
printing to standard out. 
It is usefull after editing a dii by hand.
.SH OPTIONS
none
.SH EXAMPLES
dii-renum edited.dii >fixed.dii
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
