.TH isummsize 1 isummsize\-0.0.1
.SH NAME
isummsize \- get gigabytes from ecap Discovery Summary
.SH SYNOPSIS
.B isummsize 'SAMPLE01 Discovery Summary Report.csv' 
.SH DESCRIPTION
isummsize prints gigabytes to four digit accuracy from
an IPRO ecap Discovery Summary Report.
.SH OPTIONS
none
.SH BUGS
Probably.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
