.TH statdii 1 statdii\-0.0.1
.SH NAME
statdii \- extract useful summary from a summation dii file
.SH SYNOPSIS
.B statdii DIIFILE
.SH DESCRIPTION
.B statdii
accepts a single dii file as an argument and prints
image count, tiff count, jpg count, range etc to 
standard out.
.SH OPTIONS
none
.SH EXAMPLES
statdii example.dii
.SH FILES
.SH SEE ALSO
.SH BUGS
Essentially vaporware.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
