.TH lfp2csv 1 lfp2csv\-0.0.1
.SH NAME
lfp2csv \- convert IM lines of an lfp to csv
.SH SYNOPSIS
.B lfp2csv LFPFILE
.SH DESCRIPTION
lfp2csv accepts an lfp on standard in,
or specified on the command line,
and prints a csv on standard out. 
This is handy for performing joins, etc.
.SH OPTIONS
none
.SH BUGS
Probably.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
