.TH txt2ss 1 txt2ss\-0.0.1
.SH NAME
txt2ss \- generate a nicely formatted slipsheet pdf from plain text
.SH SYNOPSIS
.B txt2ss [-n] FILE
.SH DESCRIPTION
txt2ss reads a list from standard in or 
.B FILE,
and generates a pdf with each line as a nice looking page.
.SH OPTIONS
.B -n
Make newlines for each backslash.
.SH EXAMPLES
txt2ss folder-list.txt
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
