.TH lfp2begend 1 lfp2begend\-0.0.1
.SH NAME
lfp2begend \- create begin - end ranges from lfps
.SH SYNOPSIS
.B lfp2begend FILE
.SH DESCRIPTION
lfp2begend takes an lfp file or files and prints begin - end ranges
to the file Beg End.txt
with dos-style line endings.
Beg End.txt will be overwritten if it exists.
.SH OPTIONS
none
.SH EXAMPLES
lfp2begend FILE
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
