.TH watch-iexport 1 watch-iexport\-0.0.1
.SH NAME
watch-iexport \- wait for an Ipro ecap export to complete
.SH SYNOPSIS
.B watch-iexport [STRING]
.SH DESCRIPTION
watch-iexport waits for an Ipro ecap export to complete
under the current directory. 
Really, is is just waiting for the Volume Manifest to be created.
Optionally, a custom string can be emmited on standard out whilst waiting.
.SH EXAMPLES
watch-iexport 
.SH FILES
.SH SEE ALSO
.SH BUGS
Should probably check the error report for `real' errors.
Probably others.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
