.TH fd-fold 1 fd-fold\-0.0.1
.SH NAME
fd-fold \- generate a shell script to refolder pdfs based on lfp FD flags.
.SH SYNOPSIS
.B fd-fold [-x] LFPFILE
.SH DESCRIPTION
fd-fold generates a shell script to refolder pdfs
based on FD tags in an lfp.
.SH OPTIONS
.B -x
Run script after generating it.
.SH FILES
.B refold.sh
The generated script.
.SH SEE ALSO
.SH BUGS
This man page sucks.
Probably others.
.SH LICENSE
\(co 2012, 2013 Noah Birnel
.sp
You may use this software however you like.
