#!/bin/sh

warn() {
    echo "$@" 1>&2
}

die() {
    status=$1
    shift
    warn "$@"
    exit $status
}

mover="refold.sh"
lfp="$1"
while [ $# -gt 0 ]; do
    case "$1" in
      -x)
        executable=1
        shift
        ;;
      --)
        shift
        break 2
        ;;
      -*)
        die 1 "unknown flag $1"
        ;;
      *)
        break 2
        ;;
    esac
done

echo '#!/bin/sh' >"$mover"

grep '\(^IM,.*,[A-Z],\)\|\(^FD,\)' "$lfp" | sort -t, -k2,2 -k1,1 |\
awk '
BEGIN { FS = "," }

/^FD,/ { 
    fold = $4
    printf("mkdir \"%s\"\n", fold)
}

/^IM,/ { printf("mv -v \"%s.PDF\" \"%s\"\n", $2, fold) }
' >>"$mover" 

if [ -n "$execute" ] 
    ./"$mover"
else 
    warn "run $mover from the pdf directory" 
fi

