.TH sing2multt 1 sing2multt\-0.0.1
.SH NAME
sing2multt \- create multi-page text from single-page text ocr
.SH SYNOPSIS
.B sing2multt LFPFILE
.SH DESCRIPTION
.B sing2multt
reads a given lfp and catenates ocr files in a 
SINGLE-PAGE TEXT
directory in the current directory to a MULTI-PAGE DIRECTORY (which it
will also create for you.) 
.SH OPTIONS
none
.SH EXAMPLES
sing2multt example.lfp
.SH FILES
.SH SEE ALSO
.SH BUGS
Doesn't check to see if we are overwriting files in 
MULTI-PAGE TEXT.
.sp
Probably others.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
