.TH recolor-ibuild 1 recolor-ibuild\-0.0.1
.SH NAME
recolor-ibuild \- combine a color build and a black and white build
.SH SYNOPSIS
.B recolor-ibuild [--skip-coloryank] COLORDIR BNWDIR
.SH DESCRIPTION
recolor-ibuild creates a new lfp from the two input builds,
and places it in a combined directory.
.SH OPTIONS
.B --skip-coloryank
assume the color has already been culled before running this script
.SH SEE ALSO
coloryank(1)
.SH BUGS
Written in bash.
Probably others.
.SH LICENSE
\(co 2012, 2013 Noah Birnel
.sp
You may use this software however you like.
