#!/usr/bin/bash

die() {
    status="$1"
    shift
    warn "$@"
    exit "$status"
}

warn() {
    echo "$@" 1>&2
}

yankit() {
    (
    cd "$clr" || die 1 "Can't change directories to $clr"
    warn Copying out our color
    mkdir color || die 1 "Can't make $clr/color"
    cp -v IMAGES/*/*/*[Jj][Pp][Gg] color/
    warn Please review, rotate, and cull your color in:
    warn "$clr"/color
    warn Press any key when you are done culling...
    cygstart "$clr"

    read
    )
}

yank=1

while [ "$#" -gt 2 ]; do
    case "$1" in 
      --skip-coloryank)
        yank=0
        shift
        ;;
      --)
        shift
        break
        ;;
      *)
        die 1 "unkown flag"
        shift 
        break
        ;;
    esac
done
       
clr="$1"
bnw="$2"

test "$yank" -eq 1 && yankit

ls "$clr"/color | sort -u | sed 's/\.[Jj][Pp][Gg]$//' >colorlist

#FIXME we'll have to join the colorlist with the bnw lfp
#      to figure out where to put the jpgs. sigh.

#extract the color
d2u < "$clr"/DATA/*.LFP | grep '^IM,' | sort -t, -k2,2 |\
join -t, -12 -21 -o'1.1 1.2 1.3 1.4 1.5' - colorlist > color.lfp.tmp
( cd "$clr"/DATA/ && mkdap )

#extract the not color
d2u < "$bnw"/DATA/*.LFP | grep '^IM,' | sort -t, -k2,2 |\
join -t, -12 -21 -o'1.1 1.2 1.3 1.4 1.5' -v1 - colorlist > bnw.lfp.tmp
( cd "$bnw"/DATA/ && mkdap )

#and mix them together
mkdir combined
combined_lfp=combined/combined.lfp
sort -t, -k2,2 bnw.lfp.tmp color.lfp.tmp | u2d > $combined_lfp
cat "$clr"/DATA/direct_access.lfp >>$combined_lfp
cat "$bnw"/DATA/direct_access.lfp >>$combined_lfp

warn "Use $combined_lfp"


