#!/usr/bin/bash

die() {
    status="$1"
    shift
    warn "$@"
    exit "$status"
}

warn() {
    echo "$@" 1>&2
}

yankit() {
    (
    cd "$clr" || die 1 "Can't change directories to $clr"
    warn Copying out our color
    mkdir color || die 1 "Can't make $clr/color"
    cp -v IMAGES/*/*/*[Jj][Pp][Gg] color/
    warn Please review, rotate, and cull your color in:
    warn "$clr"/color
    warn Press any key when you are done culling...
    cygstart "$clr"

    read
    )
}

yank=1

while [ "$#" -gt 2 ]; do
    case "$1" in 
      --skip-coloryank)
        yank=0
        shift
        ;;
      --)
        shift
        break
        ;;
      *)
        die 1 "unkown flag"
        shift 
        break
        ;;
    esac
done
       
clr="$1"
bnw="$2"

test "$yank" -eq 1 && yankit

ls "$clr"/color | sort -u | sed 's/\.[Jj][Pp][Gg]$//' >colorlist

#FIXME we'll have to join the colorlist with the bnw lfp
#      to figure out where to put the jpgs. sigh.

#extract the color
d2u < "$clr"/DATA/*.[Ll][Ff][Pp] | grep '^IM,' | sort -t, -k2,2 |\
join -t, -12 -21 -o'1.1 1.2 1.3 1.4 1.5' - colorlist > color.lfp.tmp

#extract the not color
d2u < "$bnw"/DATA/*.[Ll][Ff][Pp] | grep '^IM,' | sort -t, -k2,2 |\
join -t, -12 -21 -o'1.1 1.2 1.3 1.4 1.5' -v1 - colorlist > bnw.lfp.tmp

#and mix them together
sort -t, -k2,2 bnw.lfp.tmp color.lfp.tmp | u2d > "$bnw"/DATA/color.lfp

#and put the jpgs where the new lfp can find them
warn "Copying billable color to it's new home. Could be slow!"

sed '
s#\\#/#g;
s#[^;]*;\([^;]*\);\([^;]*\);.*#cp -uv "'"$clr"'/color/\2" "'"$bnw"'/\1/"#
' color.lfp.tmp >mover.sh

#FIXME don't move the color at all, just add direct access paths 
#FIXME This is not so safe what with umask 000.
. ./mover.sh

warn "If you used different project names for your builds,"
warn "you'll need to "
warn '$EDITOR' "$bnw/DATA/color.lfp"


