.TH meta2folders 1 meta2folders\-0.0.1
.SH NAME
meta2folders \- recreate native folders from metadata
.SH SYNOPSIS
.B meta2folders METADATA
.SH DESCRIPTION
meta2folders generates a shell script to move ouput
files into recreations of ecap LOCATION data.
.SH OPTIONS
none
.SH EXAMPLES
meta2folders metadata.csv && ./folds.sh
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
