.TH list2header 1 list2header\-0.0.1
.SH NAME
list2header \- make a csv header from a list
.SH SYNOPSIS
.B list2header [FILE]
.SH DESC.LPTION
.B list2header
takes a list of field names,
one per line, 
on standard in or from
.B FILE
and generates a csv header from it.
.SH OPTIONS
none
.SH EXAMPLES
.SH SEE ALSO
.B awk(1)
.SH BUGS
Probably.
.SH LICENSE
\(co 2013 Noah Birnel
.sp
You may use this software however you like.
