.TH lfppath2issues 1 lfppath2issues\-0.0.1
.SH NAME
lfppath2issues \- create an issues lfp from another lfp
.SH SYNOPSIS
.B lfppath2issues LFPFILE
.SH DESCRIPTION
lfppath2issues accepts an image import lfp and generates
an lfp of issue tags from the import filenames.
.SH OPTIONS
none
.SH EXAMPLES
lfppath2issues LFPFILE
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
