.TH statvstats 1 statvstats\-0.0.1
.SH NAME
statvstats \- extract useful summary from an IPRO vstats or bstats file
.SH SYNOPSIS
.B statvstats VSTATSFILE
.SH DESCRIPTION
.B statvstats
accepts a single vstats or bstats csv 
file as an argument and prints
whatever summary information it can get from it.
.SH OPTIONS
none
.SH EXAMPLES
statvstats example_vstats.csv
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
