#!/usr/bin/env perl
use strict;
use warnings;
use Getopt::Std;
use vars qw($opt_x);

my $execute = 0;
my $colordir = "color";

getopts('x');
if ($opt_x) { $execute = 1;  }


if ( -d $colordir ) {
    warn "Color directory exists: $!";
} elsif ( -e $colordir ) {
    die "$colordir is not a directory: $!";
} else {
    mkdir $colordir;
}


open SCRIPT, ">colorcp.sh" or die "Can't open colorcp.sh: $!";

LINE: while (<>) {
    /^IM.*\.jpg;4/i or next LINE;
    s,\\,/,g;
    s,','"'"',g;
    my @a = split /;/;
    printf SCRIPT "cp -vu '%s/%s' color/\n", $a[1], $a[2];
}

chmod 0755, "colorcp.sh" or die "Can't chmod colorcp.sh: $!";

$execute && ( system("./colorcp.sh") == 0
        or die "system ./colorcp.sh failed: $?" )

