.TH doc2pdf 1 doc2pdf\-0.0.1
.SH NAME
doc2pdf \- generate pdfs from ms word files.
.SH SYNOPSIS
.B doc2pdf DOC [DOC...]
.SH DESCRIPTION
doc2pdf creates pdfs from ms word files, 
using native ms word 2007(+)
and the "save as pdf" plugin.
.SH OPTIONS
none
.SH FILES
/usr/local/etc/doc2pdf/doc2pdf.vbs
.br
The visual basic script laying underneath this script.
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2011 Noah Birnel
.sp
You may use this software however you like.
