.TH summ-refold 1 summ-refold\-0.0.1
.SH NAME
summ-refold \- place multi-page text in images folder per lfp
.SH SYNOPSIS
.B summ-refold LFPFILE
.SH DESCRIPTION
summ-refold generates a shell script on standard out 
to place multi-page text in images folders. 
This is handy for Summation jobs produced by Ipro.
It should be run from the root of the volume.
.SH OPTIONS
none
.SH EXAMPLES
summ-refold DATA/VOLUME01.LFP >refold.sh && ./refold.sh
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
