.TH lfp2lst 1 lfp2lst\-0.0.1
.SH NAME
lfp2lst \- generate a summation style lst from an lfp
.SH SYNOPSIS
.B lfp2lst [-m] LFPFILE
.SH DESCRIPTION
lfp2lst prints an lst to standard out from an lpf 
supplied on the command line.
.SH OPTIONS
.B -m
put subfolders in the lst file
.SH EXAMPLES
lfp2lst sample.lfp >sample.lst
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
