.TH xmpp2csv 1 xmpp2csv\-0.0.1
.SH NAME
xmpp2csv \- convert an xmpp to a csv, and break it per record
.SH SYNOPSIS
.B xmpp2csv FILE
.SH DESCRIPTION
xmpp2csv prints a csv with all fields to standard out from
an xmpp file supplied on the command line.
It also generates text files,
one per record.
.SH OPTIONS
none
.SH EXAMPLES
xmpp2csv input.xmpp > output.csv
.SH BUGS
Probably.
.SH LICENSE
\(co 2012 Noah Birnel
.sp
You may use this software however you like.
